<a href="https://colab.research.google.com/github/anefthma/Assignments/blob/master/Copy_of_DSPT3_WarmUp_9_17_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DSPT3 Warm Up

## All questions in this code challenge refer to the dataframe below.

                                                                                .

In [0]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/ValerieLangat/CC-DSPT3/master/Cars%20-%20Sheet1.csv')

In [36]:
df.head()

  Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...    2705  non-USA  Acura Integra
1        Acura   Legend  Midsize  ...    3560  non-USA   Acura Legend
2         Audi       90  Compact  ...    3375  non-USA        Audi 90
3         Audi      100  Midsize  ...    3405  non-USA       Audi 100
4          BMW     535i  Midsize  ...    3640  non-USA       BMW 535i

[5 rows x 27 columns]

## Question 1:
### Find the max and min values of the passengers column *without* using df.describe()

In [0]:
def MAX(x):
  return(max(x))
         
def MIN(x):
         return(min(x))

In [33]:
MAX(df.Passengers)

8

In [34]:
MIN(df.Passengers)

2

## Question 2:
### Using the same dataset, create both a crosstab and a pivot table. When might one be better to use than the other?

In [43]:
ct = pd.crosstab(df.Weight, df['MPG.highway'])
ct

MPG.highway  20  21  22  23  24  25  26  27  ...  34  36  37  38  41  43  46  50
Weight                                       ...
1695          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   1
1845          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
1965          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   1   0   0
2045          0   0   0   0   0   0   0   0  ...   0   0   1   0   0   0   0   0
2055          0   0   0   0   0   0   0   0  ...   0   0   1   0   0   0   0   0
2240          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2270          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2285          0   0   0   0   0   0   0   0  ...   1   0   0   0   0   0   0   0
2295          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2325          0   0   0   0   0   0   0   0  ...   0   0   1   0   0   0   0   0
2345          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2350          0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   1   0
2440          0   0   0   0   0   0   0   0  ...   0   1   0   0   0   0   0   0
2450          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
2475          0   0   0   0   0   0   0   0  ...   0   1   0   0   0   0   0   0
2490          0   0   0   0   0   0   0   0  ...   0   1   0   0   0   0   0   0
2495          0   0   0   0   0   0   0   0  ...   0   0   0   1   0   0   0   0
2530          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2545          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2575          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2620          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2640          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2670          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2690          0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   0
2705          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2710          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
2775          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
2785          0   0   0   0   0   0   0   0  ...   1   0   0   0   0   0   0   0
2810          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
2850          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
...          ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
3380          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
3405          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3450          0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   0
3470          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3490          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3495          0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   0
3510          0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   0
3515          0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   0
3525          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
3560          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
3570          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3610          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3620          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
3640          0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3695          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3705          0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3715          0   0   0   2   0   0   0   0  ...   0   0   0   0   0   0   0   0
3730          0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   0
3735          1   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   0
3785          0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3805          0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   0
3910          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3935          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
3950          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3960          0   1   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
4000          0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
4025          1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
4055          0   0   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
4100          0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   0
4105          0   0   0   0   0   1   0   0  ...   0   0   0   0   0   0   0   0

[81 rows x 22 columns]

In [89]:
pd.pivot_table(df['Price'], df['MPG.highway'])

AttributeError: ignored

                                                                      .

## Question 3: 
### Let's practice some filtering. In our main dataframe, which manufacturer, model and type of car has the highest reported Price? (hint: checkout df.loc)

### What is the exact row and column number of the cell containing the highest reported Price? Please print that value.

In [58]:
df.head()

  Manufacturer    Model     Type  ...  Weight   Origin           Make
0        Acura  Integra    Small  ...    2705  non-USA  Acura Integra
1        Acura   Legend  Midsize  ...    3560  non-USA   Acura Legend
2         Audi       90  Compact  ...    3375  non-USA        Audi 90
3         Audi      100  Midsize  ...    3405  non-USA       Audi 100
4          BMW     535i  Midsize  ...    3640  non-USA       BMW 535i

[5 rows x 27 columns]

                                                  .

In [93]:
MAX(df['Max.Price'])

80.0

In [95]:
df.loc[df['Max.Price'] > 79]

     Manufacturer Model     Type  ...  Weight   Origin                Make
58  Mercedes-Benz  300E  Midsize  ...    3525  non-USA  Mercedes-Benz 300E

[1 rows x 27 columns]

## Question 4: 
### Get creative! Use any library you'd like to practice making plots. If you have extra time, try to incorporate color or something cool you've found that we haven't reviewed in class yet. Have fun with this and let's get some volunteers to show off their creations :)

In [0]:
mpgbin = pd.cut(df['MPG.highway'], 10)
pricebin = pd.cut(df[''])